spring:
  application:
    name: WalletAndSettlement


  datasource:
    url: jdbc:mariadb://localhost:3306/wallet_and_settlement?createDatabaseIfNotExist=true
    username: root
    password: fredsystem
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update # or create, create-drop, none
    show-sql: true
  rabbitmq:
    host: localhost
    port: 5672
    username: myuser
    password: secret


server:
  port: 8080

files:
  external-transaction-file-location: classpath:files

rabbitmq:
  queue:
    name: transactions
  exchange:
    name: transaction_exchange
  routing:
    key: txn
