spring:
  application:
    name: WalletAndSettlement

  sql:
    init:
      mode: always
      platform: mariadb
      continue-on-error: true

  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update

  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: 5672
    username: ${RABBITMQ_USER}
    password: ${RABBITMQ_PASSWORD}
    listener:
      simple:
        retry:
          enabled: false
        default-requeue-rejected: false


server:
  port: 8080

files:
  external-transaction-file-location: ${RESOURCES_DIR}/files

rabbitmq:
  queue:
    name: transactions
  exchange:
    name: transaction_exchange
  routing:
    key: txn
