spring:
  application:
    name: WalletAndSettlement

  datasource:
    url: jdbc:mariadb://localhost:3306/wallet_and_settlement
    username: root
    password: fredsystem
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update # or create, create-drop, none
    show-sql: true

server:
  port: 8080

files:
  external-transaction-file-location: classpath:files
